### ISSUE TITLE
Links dont work when organized folder is outside of _Arcade

### ISSUE THREAD

**Issue by edru** [MAME-GETTER/_arcade-organizer#1]
Using the INI file I placed my Organized folder in /media/fat so I could just have a "root level" organized folder - but it seems when the links are created in that manner, they do not work.

If i run the script and tell it a location within _Arcade it works fine.

The goal was to have it land as /media/fat/_Arcade-Organized

**Comment by MAME-GETTER** [comment]
The final directory must be named _Organized. _Arcade-Organized will not work.

**Comment by MAME-GETTER** [comment]
I would recommend you use the default path.

If you want somthing in the root directory make a symlink for it to the default path.

You can use these command from an ssh session to MiSTer to set it up.

```cd /media/fat
ln -s /media/fat/_Arcade/_Organized _Arcade-Organized```

**Comment by edru** [comment]
Thanks for the info on the symlink will give that a shot.
