### ISSUE TITLE
Can't find 'Robotron 2084' under Manufacturer 'Williams'

### ISSUE THREAD

**Issue by reset-selectgame-1-9** [MAME-GETTER/_arcade-organizer#24]
'Robotron 2084' isn't listed when searching under Manufacturer 'Williams'.

**Comment by MAME-GETTER** [comment]
Please file this bug with the core/mra owner.

The Arcade Organizer uses the MRA file to organize. If the metadata is not listed in the MRA then the arcade organizer will organize it.

Closing
