### ISSUE TITLE
Not sorting latest Jotego CPS 1.5 games

### ISSUE THREAD

**Issue by neosquid** [MAME-GETTER/_arcade-organizer#25]
The script doesn't seem to sort these games into A-Z categories, or CAPCOM folder.

**Comment by amoore2600** [comment]
File a bug with author of the MRA file. 

The Arcade organizer only sorts based on data in the MRA file. 

MRA file should use proper XML tags and formatting.

Closing.

**Comment by MAME-GETTER** [comment]
You can also run the check MRA script. To see mrs files with missing data.

Its in the scripts directory.

Closing
