### ISSUE TITLE
Bug in directory creation when using CIFS mounted _Arcade directory on NAS (SMB)

### ISSUE THREAD

**Issue by luke7101** [MAME-GETTER/_arcade-organizer#33]
280Z-ZZAP.mra                                SpaceInvad 1976 Dave Nutti Games  N
mkdir: cannot create directory â€˜/media/fat/_Arcade/_Organized/_4 Manufacturer/_Dave Nutting Associates / Midwayâ€™: No such file or directory

I read the following part from the disclaimer, but didn't understood it related to this situation : "THESE SYMLINKS ONLY WORK ON MISTER! IF YOU MOUNT YOUR SD CARD OUTSIDE OF MISTER THESE SYMLINKS WILL NOT WORK." 
The directory is mounted with the cifs_mount.sh mister script, and the NAS has SMB protocol, maybe it's a problem with a unallowed character, a space at the end of the directory, or one of those  / \ : * ? " < > |

**Comment by MAME-GETTER** [comment]
Windows file systems do not support symlinks.

**Comment by luke7101** [comment]
Ok, so it only could work if symlinks were created on the nas itself, before mounting the shares.
I should look into the script and find if it could be adapted to run from a shell inside the synology NAS (or inside a docker with a proper linux distro inside the NAS)
