### ISSUE TITLE
D&D TOD, seems to not generate some symlinks

### ISSUE THREAD

**Issue by theypsilon** [MAME-GETTER/_arcade-organizer#35]
According to a couple of users, it misses the symlink in the Cores folder. Will have to investigate it further.

![image](https://user-images.githubusercontent.com/852246/112752941-cd4b4400-8fd5-11eb-9890-971e7f4412c9.png)

**Comment by MAME-GETTER** [comment]
I bet the & is giving it troubles

**Comment by theypsilon** [comment]
That's also what I think too.

If you see the MRA it has the following field: 
![image](https://user-images.githubusercontent.com/852246/112753630-9c204300-8fd8-11eb-8395-357aa4e0e4a9.png)

But bare & in XML are not valid. You have to use &amp; instead.

**Comment by MAME-GETTER** [comment]
I've reached out to the author of The MRA and this should be corrected soon

**Comment by MJY71** [comment]
Yes, that was exactly the reason. I had already corrected all of the D&D MRAs 3 days before this issue was submitted. It should not be a problem anymore.

![DDTOD](https://user-images.githubusercontent.com/18260997/115573388-4e6cc280-a286-11eb-9d0a-f0d2c2305dab.png)

**Comment by theypsilon** [comment]
Great, closing then
