### ISSUE TITLE
Arcade Organizer script fails since recent commits (NameError: name 'inifile' is not defined)

### ISSUE THREAD

**Issue by movisman** [MAME-GETTER/_arcade-organizer#36]
Hi there!

I just ran update_all.sh and noticed that the Arcade Organizer portion fails when it runs.

It was working fine the other day - I wonder if it is related to the most recent commit eg:
https://github.com/MAME-GETTER/_arcade-organizer/commit/48d9adf35bb4c4bf7dd496bb8c121bdb6a2b9d94

Please see the Arcade Organizer portion of the update_all.log file below.

Thanks!

```
################################################################################
#==============================================================================#
################################################################################

Downloading the most recent _arcade-organizer.sh script.
 


STARTING: _ARCADE-ORGANIZER
Traceback (most recent call last):
  File "/tmp/_arcade-organizer.sh", line 725, in <module>
    run()
  File "/tmp/_arcade-organizer.sh", line 700, in run
    config = make_config()
  File "/tmp/_arcade-organizer.sh", line 48, in make_config
    config["ini_file_path"] = Path(inifile)
NameError: name 'inifile' is not defined
FINISHED: _ARCADE-ORGANIZER



################################################################################
#==============================================================================#
################################################################################

There were some errors in the Updaters.
Therefore, MiSTer hasn't been fully updated.

Check these logs from the Updaters that failed:
 - _ARCADE-ORGANIZER

Maybe a network problem?
Check your connection and then run this script again.

End time: Mon Apr 19 10:18:42 BST 2021

Full log for more details: /media/fat/Scripts/.cache/update_all/update_all.log

```

**Comment by ACarter80** [comment]
I can confirm i also get this issue, looks like inifile variable was changed to uppercase on line 46 so is no longer found on line 48

    INIFILE=Path(original_script_path).with_suffix('.ini').absolute()
    ini_parser = configparser.ConfigParser()
    config["ini_file_path"] = Path(inifile)

**Comment by theypsilon** [comment]
Indeed, I caused this issue yesterday night by mistake. I should have fixed now. Thank you so much for letting me know!

**Comment by movisman** [comment]
Confirmed - I just re-ran the updater and now everything is fine.
Thank you so much for responding so quickly and getting it resolved!

I will close this one off. Thanks again! :thumbsup:
