### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ACarter80** [MAME-GETTER/_arcade-organizer#37]
Found another issue with last nights commit I get the following error when running update all, this is a fresh Mister setup so the Arcade Organizer has never been run successfully before, so this cache directory would not of been created from a previous run.

line 116
 self._logfile = open(self._config['ARCADE_ORGANIZER_WORK_PATH'] + "/issues.log", "w")
 FileNotFoundError: [Error 2] No Such File or directory: 'media/fat/Scripts/.cache/arcade-organizer/issues.log'

**Comment by theypsilon** [comment]
Good catch! That one should be also fixed now, Thanks!

**Comment by ACarter80** [comment]
Thanks thats fixed now!
